### PR TITLE
Add method to remove all records about an app

### PR DESCRIPTION
**Pull request by mardy**
This is part of the fix for https://github.com/ubports/ubuntu-touch/issues/385, but it might not be needed after all.

### CODE REVIEW

**Comment by NeoTheThird** [comment]
So we still need this @mardy?

**Comment by mardy** [comment]
Yes, I think we need this: the visible effects of ubports/ubuntu-touch#385 have been fixed already, but if you reinstall the application, I'm afraid that you'd see the permissions reappear and be remembered to how they were before the uninstallation.

In order to effectively remove the permissions upon uninstall (instead of just hiding them), then we need this branch.

**Comment by UniversalSuperBox** [comment]
I hate to do this, but can you remake this PR so it gets picked up by CI?

**Comment by Flohack74** [comment]
Basically just push it again with a different branch name ^^

**Comment by mardy** [comment]
No need, the problem was that the Jenkins job didn't have the `Discover pull requests from forks` option set. I've enabled it, and now it seems that CI is running.

**Comment by mardy** [comment]
All green, do I have your approval to merge it? :-)

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
