### PR TITLE
agent: prevent prompt provider FD leak

### PR DESCRIPTION
**Pull request by peat-psuwit**
The parent process must close the FD passed to a child if it no longer
needs it. This commit does so by using the already existing scope object
to close the FD as soon as the scope is left.

This makes Mir notices when the trust prompt is disappearing, which fixes
ubports/ubuntu-touch#1346 by giving the focus back to the app as soon as
possible.

This PR comes with Jenkinsfile update.

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by mardy** [comment]
Hi @peat-psuwit , are you sure this is needed? At least, I'm not closing the file descriptor in the Online Accounts service, when a trusted session is terminated:

https://github.com/ubports/ubuntu-system-settings-online-accounts/blob/xenial/online-accounts-service/mir-helper.cpp#L108

Should the fd be closed there, too?

**Comment by peat-psuwit** [comment]
I've read the mirclient's code, and it seems not to even record the received FD. Also, Alan Griffith [has confirmed in the Telegram group](https://t.me/ubports_devel/1541) that the caller owns the FD. So, yes, this is probably required, and you probably have to do the same in the Online Accounts service too.

**Comment by mardy** [comment]
> So, yes, this is probably required, and you probably have to do the same in the Online Accounts service too.

Thanks, I will do it, then!

**Review by UniversalSuperBox — APPROVED** [review]
Trust-store prompts still seem to work. Nice.

**Pull request merged**
