### PR TITLE
mir/agent: re-try prompt session with parent

### LINKED ISSUE #399: Microphone access not working
To be able to send vocal messages with Axolotl, we need to access the microphone. It looks like even with OTA-13 and the QtWebEngine upgrade, the microphone isn't working. When going to a website like https://framatalk.org/test, the access to the microphone is asked, but even after saying Yes in the UT popup to give permission, the website can't access the microphone.

Tested on a Fairphone 2 Halium 5.1 port, running the last devel build.
Same problem with my Pinephone last devel.

### LINKED ISSUE #1668: First time granting access to microphone, breaks microphone for all other apps too (qt 5.12 issue?)
Devices: Nexus 5, Fairphone 3, BQ e4.5
Channel: dev

I assume this happens since QT 5.12 update.
If your html5-app or Morph-Browser for example, already did have permission to use the microphone or are in the permissions-list displayed at least, then everything works as expected.

### Expected Behavior
- Opening html5 app / open any microphone recording page in Morph 
- website asks for permission
- when choosing "yes", system asks for permission if it is not already in the systems allowed apps.

### Current Behavior
- Starting html5 recording test app / opening any microphone recording page in Morph
- website asks for permission
  - when choosing "yes": 
    - system does not ask for permission, the app is not saved in the permissions-list for the microphone
    - No other App can use the microphone until a lomiri restart (recorder App for example)
  - when choosing "no":
    - the app is not saved in the permissions-list for the microphone
    - microphone is still usable by other apps

Here is a test html5 app:
[html5rectest.zip](https://github.com/ubports/morph-browser/files/5954267/html5rectest.zip)

related: https://github.com/luksus42/soundrecog/issues/6
maybe related: ubports/morph-browser#455 , ubports/morph-browser#399

### PR DESCRIPTION
**Pull request by peat-psuwit**
Mir expects a PID of a process that have a Mir session. Meanwhile, the
trust-store users supply us the PID of the requesting process, which
might not be the same process. For example, QtWebEngine uses a helper
process to record the audio. In this case, Mir won't be able to find a
session and fails.

What we do here is that, when we encounter such error from Mir, get the
process's parent pid, and then try again.

Thanks @mariogrip for the idea. This is the alternative to ~~#17~~ #15.

Fixes: ubports/morph-browser#399
Fixes: ubports/ubuntu-touch#1668

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
I assume this actually replaces #15, not #17?

**Comment by peat-psuwit** [comment]
Opps. Fixed.

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This seems to work, but only if morph-browser is the first application to request microphone access in a session. If any other app requests mic access before morph-browser, the prompt never appears. There is no information in the `pulseaudio-trust-stored.log`.

**Comment by peat-psuwit** [comment]
I sort of able to reproduce the hang with this PR installed once, and then doesn't appear anymore. Weird.

One may get more information by enabling pulseaudio verbose logging. To do this, run:
```sh
mkdir -p ~/.config/upstart/
echo `exec pulseaudio --start --log-target=syslog -vvv` > ~/.config/upstart/pulseaudio.override
```

The log will be available in `/var/log/syslog`.

**Comment by peat-psuwit** [comment]
@mariogrip Have you re-tested the hang reported by @UniversalSuperBox ?

**Comment by mariogrip** [comment]
> @mariogrip Have you re-tested the hang reported by @UniversalSuperBox ?

Yes i have, i cannot reproduce it.

**Comment by cibersheep** [comment]
Device: Arale
Channel: RC 2021-W45
Result: Recording a message from Telegram web in Morph works. Opening other qml apps and recording audio works. Going back to Telegram web in Morph asks again for access and audio works

**Comment by Flohack74** [comment]
@peat-psuwit removed that PR from the project board for OTA-20 and instead put on those 2 issues that you mentioned in the beginning.

**Comment by nanu-c** [comment]
On Axolotl we have a problem here, because:
Axolotl runs qmlscene that runs webengineview. For Axolotl we would need to retrigger it on the parent of the parent again, because it's also a child.

```
phablet@ubuntu-phablet:~$ ps aux | grep axolotl
phablet  27072  0.1  0.4 919240 15652 ?        Tsl  01:07   0:00 axolotl -e ut
phablet  28634  0.0  0.0  42312   920 pts/8    S+   01:11   0:00 grep --color=auto axolotl
phablet@ubuntu-phablet:~$ ps --ppid 27072
  PID TTY          TIME CMD
27082 ?        00:00:49 qmlscene
27084 ?        00:00:00 crayfish
phablet@ubuntu-phablet:~$ ps --ppid 27082
  PID TTY          TIME CMD
27111 ?        00:00:00 QtWebEngineProc
27152 ?        00:00:00 QtWebEngineProc
phablet@ubuntu-phablet:~$ ps --ppid 27111
  PID TTY          TIME CMD
27123 ?        00:01:46 QtWebEngineProc
phablet@ubuntu-phablet:~$ ps --ppid 27123
  PID TTY          TIME CMD
phablet@ubuntu-phablet:~$ ps --ppid 27152
  PID TTY          TIME CMD
phablet@ubuntu-phablet:~$ 
```

**Comment by Flohack74** [comment]
Ouch. Endless parents ^^ - If you feel that needs adressing plz open a new ticket.

**Comment by peat-psuwit** [comment]
Hmm, the code should already look for parent's parent already. Do you have a log or something? Note that one can enable Pulseaudio's verbose logging by following [this comment](https://github.com/ubports/trust-store/pull/18#issuecomment-845308906).

**Comment by nanu-c** [comment]
I am sorry for the noise, it was a qml problem and my test with talking to pulseaudio via golang also failed.

On this snippet, `onJavaScriptDialogRequested` works but `onFeaturePermissionRequested` not.

```
UITK.Page {
  WebEngineView {
    id: _webView
   [...]
   onJavaScriptDialogRequested: function(request) {
   [...]
   }
   onFeaturePermissionRequested: {
      console.log("grantFeaturePermission", feature)
      _webView.grantFeaturePermission(securityOrigin, feature, true);
    }
}
```
It need's to be: (somehow confusing for me)
```
UITK.Page {
  WebEngineView {
    id: _webView
   [...]
   onJavaScriptDialogRequested: function(request) {
   [...]
   }
  Connections {
    onFeaturePermissionRequested: {
      console.log("grantFeaturePermission", feature)
      _webView.grantFeaturePermission(securityOrigin, feature, true);
    }
  }

**Comment by Flohack74** [comment]
Ok so I confirm that this is working.

**Pull request merged**
