### PR TITLE
Remove vivid cruft

### PR DESCRIPTION
**Pull request by z3ntu**
Also some "bzr export" stuff is removed :)

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

**Comment by Flohack74** [comment]
I think no test is needed here on the device, as there was no code change. If it builds ok and did not have any noticeable regression I would close it right away. @z3ntu any ideas if this could have side effects on the device?

**Comment by z3ntu** [comment]
Nah this should be fine - not even the build process for xenial (or newer) should have changed.

**Pull request merged**
